// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputTask struct {
	Title  string `json:"title"`
	Status string `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID     int     `json:"id"`
	Title  string  `json:"title"`
	Status string  `json:"status"`
	users  []*User `json:"users"`
}

type User struct {
	ID    int     `json:"id"`
	Name  string  `json:"name"`
	tasks []*Task `json:"tasks"`
}
