// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputTask struct {
	Title  string `json:"title"`
	Status string `json:"status"`
}

type Mutation struct {
}

type Query struct {
}

type Task struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}
