// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Question struct {
	ID           string `json:"id"`
	QuestionText string `json:"questionText"`
}

type Survey struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description,omitempty"`
	Questions   []*Question `json:"questions"`
}

type SurveyQuestion struct {
	SurveyID   string `json:"survey_id"`
	QuestionID string `json:"question_id"`
}
